# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  init:
    cmds:
      - poetry install
  lint:
    cmds:
      - poetry run pylint --rcfile pylintrc .
  format:
    cmds:
      - poetry run black --line-length 120 .
