# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  lint:
    cmds:
      - poetry run pylint --rcfile pylintrc .
  format:
    cmds:
      - poetry run black --line-length 120 .
