# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  init:
    cmds:
      - poetry install
  lint:
    cmds:
      - poetry run pylint --rcfile pylintrc .
  format:
    cmds:
      - poetry run black --line-length 120 .
  prod:
    cmds:
      - poetry run waitress-serve --port=$PORT_NUMBER --call gateway.flask.factory:create_flask_app
  build-dev:
    cmds:
      - docker build -t andrewli2048/celebi-api -f docker/DevDockerfile .
  run-dev:
    cmds:
      - task: build-dev
      - docker run --rm -p 9000:9000 --name celebi-api andrewli2048/celebi-api
  build-prod:
    cmds:
      - docker build -t andrewli2048/celebi-api -f docker/ProdDockerfile .
      - docker push andrewli2048/celebi-api
  run-prod:
    cmds:
      - docker run --rm -p 9000:9000 --name celebi-api-prod andrewli2048/celebi-api
