name: "[celebi/lint] Run pylint, black, mypy, and ruff"

on:
  push:
    branches: ["main", "celebi*"]
    paths:
      - "celebi/**"
      - ".github/workflows/celebi-lint.yml"
  pull_request:
    branches: ["*"]
    paths:
      - "celebi/**"
      - ".github/workflows/celebi-lint.yml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Poetry dependencies
        working-directory: ./celebi
        run: poetry install

      - name: Run pylint on src files
        working-directory: ./celebi
        run: poetry run pylint --rcfile pylintrc .
      
      - name: Run mypy on src files
        working-directory: ./celebi
        run: poetry run mypy celebi
      
      - name: Run ruff on src files
        working-directory: ./celebi
        run: poetry run ruff check celebi

      - name: Run black on src files
        working-directory: ./celebi
        run: poetry run black --line-length 120 .
