name: "[sealeo/lint] Run clint on src files"

on:
  push:
    branches: ["main"]
    paths:
      - "sealeo/**"
  pull_request:
    branches: ["*"]
    paths:
      - "sealeo/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Poetry dependencies
        working-directory: ./espeon
        run: poetry install

      - name: Run pylint on src files
        working-directory: ./espeon
        run: poetry run pylint --rcfile pylintrc .

      - name: Run black on src files
        working-directory: ./espeon
        run: poetry run black --line-length 120 .
